# Generated by Django 2.2.6 on 2021-04-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=25, unique=True, verbose_name='Numéro de Dépense')),
                ('lumbu', models.DateTimeField(auto_now_add=True, verbose_name='Date et Heure de Dépense')),
                ('benun', models.CharField(max_length=25, verbose_name='Benificiaire')),
                ('lettre', models.CharField(max_length=55, verbose_name='Montant en lettre')),
                ('partdeux', models.DecimalField(decimal_places=5, max_digits=19, verbose_name='Montant de Dépense')),
                ('likambom', models.CharField(max_length=255, verbose_name='Motif de Dépense')),
                ('cpartdeux', models.DecimalField(decimal_places=5, max_digits=19, verbose_name='Confirmation Montant')),
                ('lignebuget', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6'), ('S7', 'S7'), ('S8', 'S8'), ('S9', 'S9'), ('S10', 'S10'), ('S11', '11'), ('S12', 'S12'), ('S13', 'S13'), ('S14', 'S14'), ('S15', 'S15'), ('S16', 'S16'), ('S17', 'S17'), ('S18', 'S18'), ('S19', 'S19'), ('S20', 'S20'), ('S21', 'S21'), ('S22', 'S22'), ('S23', 'S23')], default='S1', max_length=255, verbose_name='Ligne Budgétaire')),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=25, unique=True, verbose_name='Numéro de Dépôt')),
                ('lumbu', models.DateTimeField(auto_now_add=True, verbose_name='Date et Heure de Dépôt')),
                ('bonguo', models.DecimalField(decimal_places=5, max_digits=19, verbose_name='Montant à Dépôt')),
                ('cbonguo', models.DecimalField(decimal_places=5, max_digits=19, verbose_name='Confirmation Montant')),
            ],
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=25, unique=True, verbose_name='Numéro de Retrait')),
                ('lumbu', models.DateTimeField(auto_now_add=True, verbose_name='Date et Heure de Retrait')),
                ('bonguo', models.DecimalField(decimal_places=5, max_digits=19, verbose_name='Montant à Retirer')),
                ('cbonguo', models.DecimalField(decimal_places=5, max_digits=19, verbose_name='Confirmation Montant')),
            ],
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=25, unique=True, verbose_name='Numéro de Transfert')),
                ('lumbu', models.DateTimeField(auto_now_add=True, verbose_name='Date et Heure de Transfert')),
                ('bonguo', models.DecimalField(decimal_places=5, max_digits=19, verbose_name='Montant à Transférer')),
                ('cbonguo', models.DecimalField(decimal_places=5, max_digits=19, verbose_name='Confirmation Montant')),
            ],
        ),
    ]
